### ISSUE TITLE
BMP085 wrong pressure

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit-Raspberry-Pi-Python-Code#102]
Hello
I connect this sensor BMP085 to my Raspberry PI B+ and i have a wrong pressure. In my city is pressure about 1022hPa but my sensor BMP085 show me about 993hPa.

Temperature in my city is -2 and sensor show about -2,6
How i can calibrate this ? Please help me.

**Comment by Marsfan** [comment]
Just thought I should point out that the the code for the bmp in this repo are outdated. A new one is available at https://github.com/adafruit/Adafruit_Python_BMP

On another note. If I understand correctly. The tempature is .6 off and the barometer is around 30 off. This sounds pretty small to me, and I have read that the bmp can be a little unreliable. 

I'm worry that I cannot tell you how to fix it though, I just got mine yesterday and all I know is from reading online.

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
