### ISSUE TITLE
Driver prints emulates character into system

### ISSUE THREAD

**Issue by stefanius** [adafruit/Adafruit-Raspberry-Pi-Python-Code#113]
I found out that on my PI somthing is sending the letter 'r' into the system (like if you pressed it on the keyboard).

When checking en troubleshouting all the drivers and pins i used,  I figured out it was the driver for the 16x2 display. Even when the display (and any other wire) is attached to the Pi, it keeps sending the 'r'.

Is there a workaround for this?

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
