### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by pnovotnak** [adafruit/Adafruit-Raspberry-Pi-Python-Code#116]
[Indentation be wack](https://www.python.org/dev/peps/pep-0008/#indentation)

**Comment by scls19fr** [comment]
+1 Such a cleanup is a good idea.

```flake8 .``` raises many

    E111 indentation is not a multiple of four

(and many other kind of errors)

**Comment by ladyada** [comment]
@tdicola has a Plan to do a major cleanup of this creaky repo including pep8, py3, and pypi...its quite a pppparty :)

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
