### ISSUE TITLE
Running Alhanum4_test

### ISSUE THREAD

**Issue by waynejnaleway** [adafruit/Adafruit-Raspberry-Pi-Python-Code#118]
I receive an error saying display=AlphaNum4.AlphaNum4() 
AttributeError:  type object has no attribute 'AlphaNum4'

Using Python 2.7 on a raspberry pi

**Comment by FryGuy01** [comment]
Need more details. If you could provide a traceback it would be helpful. Based on the error it could be any number of issues. It could be that AlphaNum4 is a instance of the class and not the class itself. 

V/r,

Brett

**Comment by FryGuy01** [comment]
Or something easier, did you check to make sure you imported AlphaNum4 and make sure object exists.

V/r,

Brett

**Comment by waynejnaleway** [comment]
Problem solved after installing the file and running from the terminal mode to get by the permisions.
