### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Chriscom** [adafruit/Adafruit-Raspberry-Pi-Python-Code#134]
Traceback (most recent call last):
  File "/home/pi/Adafruit-Raspberry-Pi-Python-Code/Adafruit_PWM_Servo_Driver/Servo_Example.py", line 3, in <module>
    from Adafruit_PWM_Servo_Driver import PWM
  File "/home/pi/Adafruit-Raspberry-Pi-Python-Code/Adafruit_PWM_Servo_Driver/Adafruit_PWM_Servo_Driver.py", line 11, in <module>
    class PWM :
  File "/home/pi/Adafruit-Raspberry-Pi-Python-Code/Adafruit_PWM_Servo_Driver/Adafruit_PWM_Servo_Driver.py", line 35, in PWM
    general_call_i2c = Adafruit_I2C(0x00)
  File "/home/pi/Adafruit-Raspberry-Pi-Python-Code/Adafruit_PWM_Servo_Driver/Adafruit_I2C.py", line 43, in **init**
    self.bus = smbus.SMBus(busnum if busnum >= 0 else Adafruit_I2C.getPiI2CBusNumber())
IOError: [Errno 2] No such file or directory

I get this error when i run Servo_Example.py and it appears to be an error from line 43 of Adafruit_I2C.py. Am I missing something that I need to download onto my Raspberry Pi 2 or is it an issue with Adafruit_I2C.py?

**Comment by thoo** [comment]
Can you open Adafruit_I2C.py from the same folder? It is the first step to check symbolic link is working.

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
