### ISSUE TITLE
PWM Servo Driver not running my servos

### ISSUE THREAD

**Issue by Cypaubr** [adafruit/Adafruit-Raspberry-Pi-Python-Code#135]
Hi, I recently bought an Adafruit 16-Channel PWM / Servo HAT for my Raspberry Pi. I followed all steps to install it and configure it.
I power up the HAT and the Pi and run Servo_Example.py but nothing.

My servo is wired on the "bus" 0 and I set the min and max µS to match with servo specifications.
Debugging says :

    Reseting PCA9685 MODE1 (without SLEEP) and MODE2
    I2C: Wrote 0x00 to register 0xFA
    I2C: Wrote 0x00 to register 0xFB
    I2C: Wrote 0x00 to register 0xFC
    I2C: Wrote 0x00 to register 0xFD
    I2C: Wrote 0x04 to register 0x01
    I2C: Wrote 0x01 to register 0x00
    I2C: Device 0x40 returned 0x01 from reg 0x00
    I2C: Wrote 0x01 to register 0x00
    Setting PWM frequency to 60 Hz
    Estimated pre-scale: 100
    Final pre-scale: 101
    I2C: Device 0x40 returned 0x01 from reg 0x00
    I2C: Wrote 0x11 to register 0x00
    I2C: Wrote 0x65 to register 0xFE
    I2C: Wrote 0x01 to register 0x00
    I2C: Wrote 0x81 to register 0x00
    I2C: Wrote 0x00 to register 0x06
    I2C: Wrote 0x00 to register 0x07
    I2C: Wrote 0xF4 to register 0x08
    I2C: Wrote 0x01 to register 0x09
    I2C: Wrote 0x00 to register 0x06
    I2C: Wrote 0x00 to register 0x07
    I2C: Wrote 0xB8 to register 0x08
    I2C: Wrote 0x0B to register 0x09
    ...

**Comment by ladyada** [comment]
hiya, support is handled at the adafruit forums
forums.adafruit.com
plz post there! thx :)
