### ISSUE TITLE
Adafruit_DHT binary needs updating with RPi 2 Base address

### ISSUE THREAD

**Issue by justasrutkauskas** [adafruit/Adafruit-Raspberry-Pi-Python-Code#136]
DHT22 didn't work with RPi2 so had to update c file with RPi2 details:

`#define BCM2709_PERI_BASE        0x3f000000`

and recompile with updated bcm2835 lib (which has support for bcm2836 which is in RPi2, used 1.47 v).

Probably worth including this based on platform.

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
