### ISSUE TITLE
Continuous integration and PEP8

### ISSUE THREAD

**Issue by scls19fr** [adafruit/Adafruit-Raspberry-Pi-Python-Code#146]
Hello,

You might use continuous integration for testing that merged code respect PEP8.

Here is a `.travis.yml` file that could help

```
language: python
python: 2.7
install:
  - python setup.py install
script:
  - flake8 --version
  - flake8 --ignore=E501 Adafruit
```

so it will ensure that library can be installed (no error in `setup.py`) and that merged code respect PEP8.

with `flake8` you can use `# noqa` to disable ununsed imports for a given line.

See also
https://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code/issues/144
https://github.com/adafruit/Adafruit-Raspberry-Pi-Python-Code/issues/116

Kind regards

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
