### ISSUE TITLE
Enhancement - writeRowSane()

### ISSUE THREAD

**Issue by gavinB-orange** [adafruit/Adafruit-Raspberry-Pi-Python-Code#149]
In Adafruit_LEDBackpack/Adafruit_8x8.py function writeRowRaw() is pretty raw - that oddity where pixel 0 is controlled by the value 128 rather than 1 is just peculiar. 
I propose adding the following patch to add writeRowSane():

(venv)pi@brebpi1:~/code/matrix/Adafruit-Raspberry-Pi-Python-Code $ git diff
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
-  def writeRowSane(self, charNumber, value):
-    """
-    Sets a row of pixels using a raw 8-bit value.
-    0..128 are mapped as you'ed expect rather than
-    128 mapping around as in the raw case.
-    """
-    assert charNumber >= 0 and charNumber <=7
-    new_value = (value / 2) + ((value % 2) \* 128)
-    self.writeRowRaw(charNumber, new_value)
  +
  def clearPixel(self, x, y):
   "A wrapper function to clear pixels (purely cosmetic)"
   self.setPixel(x, y, 0)

**Comment by gavinB-orange** [comment]
file:///home/pi/patch

Attached patch file

**Comment by gavinB-orange** [comment]
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)

**Comment by gavinB-orange** [comment]
Patch as a code block so hopefully more readable:
<
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)
>

**Comment by gavinB-orange** [comment]
'<
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)
>'

**Comment by gavinB-orange** [comment]
Now as a code block so more readable :
`
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)
`

**Comment by gavinB-orange** [comment]
<code>
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)
</code>

**Comment by gavinB-orange** [comment]
```
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)
```

**Comment by gavinB-orange** [comment]
With the patch as a code block, so more readable :

```
diff --git a/Adafruit_LEDBackpack/Adafruit_8x8.py b/Adafruit_LEDBackpack/Adafruit_8x8.py
index df966dc..32c5e41 100644
--- a/Adafruit_LEDBackpack/Adafruit_8x8.py
+++ b/Adafruit_LEDBackpack/Adafruit_8x8.py
@@ -24,6 +24,16 @@ class EightByEight:
     # Set the appropriate row
     self.disp.setBufferRow(charNumber, value)
 
+  def writeRowSane(self, charNumber, value):
+    """
+    Sets a row of pixels using a raw 8-bit value.
+    0..128 are mapped as you'ed expect rather than
+    128 mapping around as in the raw case.
+    """
+    assert charNumber >= 0 and charNumber <=7
+    new_value = (value / 2) + ((value % 2) * 128)
+    self.writeRowRaw(charNumber, new_value)
+
   def clearPixel(self, x, y):
     "A wrapper function to clear pixels (purely cosmetic)"
     self.setPixel(x, y, 0)
```

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
