### ISSUE TITLE
Hardcoded reference to 0x70 address

### ISSUE THREAD

**Issue by gavinB-orange** [adafruit/Adafruit-Raspberry-Pi-Python-Code#150]
The last line of LEDBackpack.py contains an instantiation of LEDBackpack with address 0x70.
If there is no device at this address, anyone using the library gets a series of 

```
Error accessing 0x70: Check your I2C address
Error accessing 0x70: Check your I2C address
Error accessing 0x70: Check your I2C address
Error accessing 0x70: Check your I2C address
```

This fix is to remove the line, or add the usual if **name** == '**main**' condition.
Proposed patch:

```
diff --git a/Adafruit_LEDBackpack/Adafruit_LEDBackpack.py b/Adafruit_LEDBackpack/Adafruit_LEDBackpack.py
index 00d7ba6..32287bb 100644
--- a/Adafruit_LEDBackpack/Adafruit_LEDBackpack.py
+++ b/Adafruit_LEDBackpack/Adafruit_LEDBackpack.py
@@ -98,4 +98,5 @@ class LEDBackpack:
     if (update):
       self.writeDisplay()

-led = LEDBackpack(0x70)
+if __name__ == '__main__':
+    led = LEDBackpack(0x70)
```

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
