### ISSUE TITLE
Is it possible to send data to WS2812 Light strip through the Servo Hat

### ISSUE THREAD

**Issue by kelvien** [adafruit/Adafruit-Raspberry-Pi-Python-Code#151]
I have a project where I want to control multiple digital LED light strip (WS2812b), and I thought of hooking it up to my existing Servo hat since it has 16 channels to control PWM outputs. 
From this point I thought that it should be possible, but does the current library able to achieve my goal to control individual lights and its brightness ?

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
