### ISSUE TITLE
LCD over I2C display on

### ISSUE THREAD

**Issue by hmihail** [adafruit/Adafruit-Raspberry-Pi-Python-Code#152]
I am using these libraries to control a 2x16 LCD and I am able to display text on it. However, I don't know how to turn the display back light on. I am using the MCP23008 port expander, and the pinst are set as in the example code:
pin_rs=1, pin_e=2, pins_db=[3,4,5,6]

Thanks!

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
