### ISSUE TITLE
ADS1x15 mistake

### ISSUE THREAD

**Issue by pedvide** [adafruit/Adafruit-Raspberry-Pi-Python-Code#36]
Hi, there's a mistake in the register definitions in file Adafruit_ADS1x15.py.
For the ADS1015 it says in line 57:
__ADS1015_REG_CONFIG_DR_920SPS    = 0x0050
In binary that's 0000 0000 0101 0000. This sets the DR to 490SPS and the COMP_MODE to window mode!
It should be
__ADS1015_REG_CONFIG_DR_920SPS    = 0x0060

I have also updated the library to include most functions of both chips. I wrote a post in the forum, that hasn't receive much attention, but I think it would be great if you added my changes to the library.
http://forums.adafruit.com/viewtopic.php?f=19&t=38466

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
