### ISSUE TITLE
ADS1x15 python: mistakes in error messages

### ISSUE THREAD

**Issue by HamishB** [adafruit/Adafruit-Raspberry-Pi-Python-Code#76]
While searching for how to do differential sampling in continuous sampling mode (still hunting for it!) I notice that the Adafruit_ADS1x15/Adafruit_ADS1x15.py file contains many errors in the print statements for invalid sps and pga values. Often sps and pga are swapped, both in name and in the example (e.g. gives mV instead of Hz).

patch here:
  https://gist.github.com/HamishB/11246772

regards,
Hamish

**Comment by ladyada** [comment]
Thank you for the Issue!
This library has been deprecated in favor of <a href="https://github.com/adafruit/Adafruit_Blinka">our python3 Blinka library</a>. We have replaced all of the libraries that use this repo with CircuitPython libraries that are Python3 compatible, and support a <a href="https://circuitpython.org/blinka" rel="nofollow">wide variety of single board/linux computers</a>!</p>
<p>Visit <a href="https://circuitpython.org/blinka" rel="nofollow">https://circuitpython.org/blinka</a> for more information</p>
<p>CircuitPython has <a href="https://circuitpython.readthedocs.io/projects/bundle/en/latest/drivers.html" rel="nofollow">support for almost 200 different drivers</a>, and a  as well as <a href="https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h" rel="nofollow">FT232H support for Mac/Win/Linux</a>!</p>
