### ISSUE TITLE
LCDPlate  replaces \ char with ¥

### ISSUE THREAD

**Issue by rasathus** [adafruit/Adafruit-Raspberry-Pi-Python-Code#81]
Outputting a backslash to the display with something like this ...

message_output = "Progress : \" 
lcd.message(message_output)
print message_output

results in a backslash being output to the command line, but a yen symbol ¥ outputted to the display. 

Is there some sort of character encoding option I'm missing ?

**Comment by daiscog** [comment]
Did you ever figure out how to get the LCD to display a backslash?  I'm getting a Yen symbol, too...

**Comment by rasathus** [comment]
No Im afraid not.  I ended up using an alternative display in the end.
